# Generated by Django 4.0.6 on 2022-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(blank=True, null=True, verbose_name='Stock Token')),
                ('symbol', models.CharField(blank=True, max_length=225, null=True, verbose_name='Stock Symbol')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='Stock Name')),
            ],
        ),
    ]
