# Generated by Django 4.0.6 on 2022-07-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='token',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Stock Token'),
        ),
    ]
