# Generated by Django 4.0.6 on 2022-07-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0002_alter_stock_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='token',
        ),
        migrations.AddField(
            model_name='stock',
            name='rs',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Relative Strength'),
        ),
    ]
