# Generated by Django 4.0.6 on 2022-07-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0003_remove_stock_token_stock_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Stock name'),
        ),
    ]
