# Generated by Django 4.0.6 on 2022-07-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0004_alter_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='rs',
        ),
        migrations.AddField(
            model_name='stock',
            name='rs_21',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Relative Strength 21'),
        ),
        migrations.AddField(
            model_name='stock',
            name='rs_55',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Relative Strength 55'),
        ),
    ]
