# Generated by Django 4.0.6 on 2022-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0006_alter_stock_rs_21_alter_stock_rs_55'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rs_21',
            field=models.FloatField(blank=True, null=True, verbose_name='Relative Strength 21'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='rs_55',
            field=models.FloatField(blank=True, null=True, verbose_name='Relative Strength 55'),
        ),
    ]
