# Generated by Django 4.0.6 on 2022-07-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0010_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angle_stocks.stock', unique_for_date='delivery_date'),
        ),
    ]
