# Generated by Django 4.0.6 on 2022-07-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angle_stocks', '0012_alter_delivery_delivery_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angle_stocks.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('stock', 'delivery_date')},
        ),
    ]
